# Generated by Django 4.1.5 on 2023-01-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=20, verbose_name="usuario")),
                ("correo", models.TextField(verbose_name="e-mail")),
                (
                    "contraseña",
                    models.CharField(max_length=8, verbose_name="contraseña"),
                ),
                (
                    "nomCliente",
                    models.CharField(max_length=40, verbose_name="Nombre del cliente"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=100, verbose_name="Dirrecion"),
                ),
                (
                    "telefono",
                    models.CharField(max_length=13, verbose_name="Numero de telefono"),
                ),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomDepartamento",
                    models.CharField(
                        max_length=10, verbose_name="Nombre del departamento"
                    ),
                ),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="marca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "marca",
                    models.CharField(max_length=40, verbose_name="Nombre de la marca"),
                ),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="prenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField(verbose_name="precio de la prenda")),
                ("cantidad", models.IntegerField(verbose_name="cantidad a comprar")),
                ("imagen", models.ImageField(upload_to="img", verbose_name="imagen")),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nucleo.marca"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nomProveedor",
                    models.CharField(
                        max_length=15, verbose_name="Nombre del proveedor"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(max_length=13, verbose_name="Numero de telefono"),
                ),
                ("correo", models.TextField(verbose_name="e-mail")),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="talla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("talla", models.CharField(max_length=3, verbose_name="Talla")),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(verbose_name="fecha de la compra")),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nucleo.cliente"
                    ),
                ),
                (
                    "prenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nucleo.prenda"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prenda",
            name="talla",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="nucleo.talla"
            ),
        ),
    ]
