# Generated by Django 4.1.5 on 2023-02-02 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="marca",
            options={
                "ordering": ["-create"],
                "verbose_name": "marca",
                "verbose_name_plural": "marcas",
            },
        ),
        migrations.AlterModelOptions(
            name="prenda",
            options={
                "ordering": ["-create"],
                "verbose_name": "prenda",
                "verbose_name_plural": "prendas",
            },
        ),
        migrations.AlterModelOptions(
            name="talla",
            options={
                "ordering": ["-create"],
                "verbose_name": "talla",
                "verbose_name_plural": "tallas",
            },
        ),
        migrations.AlterField(
            model_name="prenda",
            name="imagen",
            field=models.ImageField(upload_to="imgMujer", verbose_name="imagen"),
        ),
        migrations.AlterField(
            model_name="prenda",
            name="marca",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="nucleo.marca",
                verbose_name="nombre de la marca",
            ),
        ),
        migrations.CreateModel(
            name="prenda_casual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precio", models.FloatField(verbose_name="precio de la prenda")),
                ("cantidad", models.IntegerField(verbose_name="cantidad a comprar")),
                (
                    "imagen",
                    models.ImageField(upload_to="imgMujer", verbose_name="imagen"),
                ),
                (
                    "create",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "update",
                    models.DateField(auto_now=True, verbose_name="Fecha edicion"),
                ),
                (
                    "marca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nucleo.marca",
                        verbose_name="nombre de la marca",
                    ),
                ),
                (
                    "talla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nucleo.talla"
                    ),
                ),
            ],
            options={
                "verbose_name": "prenda casual",
                "verbose_name_plural": "prendas casuales",
                "ordering": ["-create"],
            },
        ),
    ]
