# Generated by Django 4.1.5 on 2023-02-02 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nucleo", "0003_rename_marca_prenda_marcas_delete_prenda_casual"),
    ]

    operations = [
        migrations.RenameField(
            model_name="prenda",
            old_name="marcas",
            new_name="marca",
        ),
    ]
